export const eventSeed = {
  id: "galaxia-2025",
  title: "GALAXIA",
  subtitle: "WHERE MUSIC MEETS THE COSMOS",
  description: "Three days. Four stages. Fifty thousand souls under one nebula sky. The largest college music festival returns for its most electrifying edition yet.",
  date: "Dec 19–21 · 2025",
  venue: "Western College of Business Management",
  address: "Western College Campus, Main Ground, Mumbai, Maharashtra",
  college_name: "Western College of Business Management",
  contact_email: "hello@galaxiafest.in",
  contact_phone: "+91 98765 43210",
  instagram_url: "#",
  youtube_url: "#",
  x_url: "#",
  hero_cta: "Reserve My Pass",
  hero_secondary_cta: "Watch Highlights",
  about_title: "A festival out of this world.",
  about_text1: "Galaxia is not just a festival — it is an interstellar rite of passage. Born on a college campus in 2013 with a single stage and a dream, we have become the most anticipated cultural gathering in the region.",
  about_text2: "From bass-shaking headliners and student anthems, to hackathons under the stars, cosplay parades, cinema on the lawn and midnight art installations — every corner of Galaxia is designed to feel like stepping through a wormhole into a universe built by, and for, the next generation.",
  seo_title: "Galaxia 2025 — Where Music Meets the Cosmos",
  seo_description: "Galaxia is the premier college music festival by Western College of Business Management — a galactic fusion of sound, light, and celebration.",
}

export const passesSeed = [
  {
    id: "regular",
    slug: "regular",
    name: "Regular",
    price: 499,
    description: "General admission — common & back rows",
    benefits: ["General entry — all 3 days", "Back rows & standing zone", "Access to 4 stages", "Food court access"],
    capacity: 2000,
    sold_count: 342,
    is_active: true,
    display_order: 1,
    color: "from-white/10 to-white/5",
    accent: "#9CA3AF",
  },
  {
    id: "silver",
    slug: "silver",
    name: "Silver",
    price: 999,
    description: "Mid-tier — middle rows, elevated view",
    benefits: ["Everything in Regular", "Middle rows reserved", "Priority entry lane", "Exclusive Silver lounge"],
    capacity: 800,
    sold_count: 412,
    is_active: true,
    display_order: 2,
    color: "from-slate-300/20 via-cyan-400/20 to-blue-500/20",
    accent: "#22D3EE",
  },
  {
    id: "gold",
    slug: "gold-premium",
    name: "Gold Premium",
    price: 1999,
    description: "Front rows — closest to stage, premium",
    benefits: ["Everything in Silver", "Front rows — closest to stage", "Meet & greet lottery", "Premium bar + merch kit", "Backstage photo zone"],
    capacity: 300,
    sold_count: 178,
    is_active: true,
    display_order: 3,
    color: "from-amber-400/30 via-fuchsia-500/20 to-purple-600/30",
    accent: "#F59E0B",
  },
]

export const artistsSeed = [
  {
    id: "shreya",
    name: "SHREYA GHOSHAL",
    genre: "Classical · Playback",
    role: "Cosmos Stage · Fri 19",
    year: "2025",
    bio: "A voice that stops galaxies. Pristine vocals and orchestral arrangement like starlight condensed into sound.",
    image_url: "https://images.unsplash.com/photo-1522863602463-afebb8886ab2?auto=format&fit=crop&w=600&q=80",
    instagram_url: "#",
    spotify_url: "#",
    youtube_url: "#",
    display_order: 1,
    featured: false,
    // inner-most — smallest, deliberate concentric, collision-safe (core + gap)
    size: 48, orbit: 288, duration: 118, startAngle: 200, spin: 7, label: "#14F195", glow: "rgba(20,241,149,0.72)", accent: "#6EE7B7",
  },
  {
    id: "neha",
    name: "NEHA KAKKAR",
    genre: "Pop · Bollywood",
    role: "Cosmos Stage · Fri 19",
    year: "2025",
    bio: "Chart-topping pop powerhouse. Non-stop dance floor bangers that keep 50,000 phones in the air.",
    image_url: "https://images.unsplash.com/photo-1520872024865-3ff2805d8bb3?auto=format&fit=crop&w=600&q=80",
    instagram_url: "#",
    spotify_url: "#",
    youtube_url: "#",
    display_order: 2,
    featured: false,
    size: 58, orbit: 373, duration: 102, startAngle: 260, spin: 6, label: "#00E5FF", glow: "rgba(0,229,255,0.70)", accent: "#67E8F9",
  },
  {
    id: "apdhillon",
    name: "AP DHILLON",
    genre: "Punjabi · R&B",
    role: "Void Stage · Sun 21",
    year: "2025",
    bio: "Modern Punjabi wave defined. Moody synths, hazy vocals — closing set built for legend status.",
    image_url: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=600&q=80",
    instagram_url: "#",
    spotify_url: "#",
    youtube_url: "#",
    display_order: 3,
    featured: false,
    size: 78, orbit: 473, duration: 84, startAngle: 320, spin: 5.5, label: "#FF6B9E", glow: "rgba(255,107,158,0.68)", accent: "#FDA4AF",
  },
  {
    id: "raftaar",
    name: "RAFTAAR",
    genre: "Hip-Hop · Rap",
    role: "Void Stage · Sat 20",
    year: "2025",
    bio: "Delhi-born hip-hop machine. Machine-gun flows and a live show engineered to level a football field of college kids.",
    image_url: "https://images.unsplash.com/photo-1591251436930-a1e858c633a1?auto=format&fit=crop&w=600&q=80",
    instagram_url: "#",
    spotify_url: "#",
    youtube_url: "#",
    display_order: 4,
    featured: true,
    size: 92, orbit: 590, duration: 72, startAngle: 140, spin: 4.2, label: "#8B5CF6", glow: "rgba(139,92,246,0.72)", accent: "#C084FC",
  },
  {
    id: "diljit",
    name: "DILJIT DOSANJH",
    genre: "Punjabi · Global Pop",
    role: "Main Stage Co-Headliner · Sat 20",
    year: "2025",
    bio: "Global Punjabi icon. From Coachella to the cosmos — stadium-scale set fusing folk, hip-hop and pop.",
    image_url: "https://images.unsplash.com/photo-1587397845856-e6cf49176c70?auto=format&fit=crop&w=600&q=80",
    instagram_url: "#",
    spotify_url: "#",
    youtube_url: "#",
    display_order: 5,
    featured: true,
    // large outer-mid — distinct amber glow for Punjabi global pop
    size: 132, orbit: 734, duration: 96, startAngle: 60, spin: 4.8, label: "#FFB800", glow: "rgba(255,184,0,0.74)", accent: "#FCD34D",
  },
  {
    id: "arijit",
    name: "ARIJIT SINGH",
    genre: "Bollywood · Playback",
    role: "Main Stage Headliner · Sun 21",
    year: "2025",
    bio: "The voice of a generation. Arijit's soulful anthems have soundtracked a decade of Indian cinema. Expect goosebumps under the stars.",
    image_url: "https://images.unsplash.com/photo-1595422656857-ced3a4a0ce25?auto=format&fit=crop&w=600&q=80",
    instagram_url: "#",
    spotify_url: "#",
    youtube_url: "#",
    display_order: 6,
    featured: true,
    // outermost — largest, 3.08x vs smallest (148/48), saturated magenta
    size: 148, orbit: 906, duration: 118, startAngle: 20, spin: 5.2, label: "#FF1A75", glow: "rgba(255,26,117,0.72)", accent: "#F9A8D4",
  },
]

export const scheduleSeed = [
  { id: "s1", time: "Fri 19 — 04:00 PM", title: "Cosmic Gates Open", description: "Wristband collection & nebula entrance", venue: "Main Ground", display_order: 1 },
  { id: "s2", time: "Fri 19 — 07:00 PM", title: "Shreya Ghoshal · Neha Kakkar", description: "Cosmos Stage double header", venue: "Cosmos Stage", display_order: 2 },
  { id: "s3", time: "Sat 20 — 06:30 PM", title: "Raftaar · Diljit Dosanjh", description: "Hip-hop to global Punjabi takeover", venue: "Main + Void Stage", display_order: 3 },
  { id: "s4", time: "Sun 21 — 08:00 PM", title: "Arijit Singh · AP Dhillon", description: "Grand finale under the nebula sky", venue: "Main Stage", display_order: 4 },
]

export const faqsSeed = [
  { id: "f1", question: "Where is Galaxia held?", answer: "At Western College of Business Management campus, Main Ground. Exact map pins will be emailed after booking.", display_order: 1 },
  { id: "f2", question: "Are passes per day or for all 3 days?", answer: "All passes cover all 3 days (Dec 19–21). Single-day upgrades can be requested at the help desk.", display_order: 2 },
  { id: "f3", question: "What’s the difference between Regular / Silver / Gold?", answer: "Regular = back/standing, Silver = middle reserved + lounge, Gold Premium = front rows + meet & greet lottery + merch kit.", display_order: 3 },
  { id: "f4", question: "Can I transfer my pass?", answer: "Passes are tied to email/phone but transfer is allowed until Dec 18 via support.", display_order: 4 },
  { id: "f5", question: "Is there an age limit?", answer: "Open to all college students & guests. Carry valid college ID.", display_order: 5 },
  { id: "f6", question: "Refunds?", answer: "Full refund until Dec 10, 50% until Dec 15, no refund after door opens.", display_order: 6 },
]

export const statsSeed = [
  { label: "Editions", value: 12, suffix: "+", icon: "star" },
  { label: "Visitors", value: 50000, suffix: "+", icon: "users" },
  { label: "Colleges", value: 120, suffix: "+", icon: "building" },
  { label: "Events", value: 55, suffix: "+", icon: "music" },
  { label: "Sponsors", value: 35, suffix: "+", icon: "trophy" },
]
